from flask_app.config.mysqlconnection import MySQLConnection
from flask_app import DATABASE
# !!! Import FILES to prevent circular import !!!
from flask_app.controllers import dojos_controller as dc
from flask_app.models import ninja_model as nm


# Model for instanciating Dojo data
class Dojo:
    def __init__(self, data):
        self.id = data['id']
        self.name = data['name']
        self.created_at = data['created_at']
        self.updated_at = data['updated_at']

    # Get all dojos
    @classmethod
    def get_all(cls):
        query = """
            SELECT *
            FROM dojos
        """
        response = MySQLConnection(DATABASE).query_db(query)
        output = []
        if response:  # ensure we're getting data
            for dojo in response:
                # Instanciate each dojo from the response
                # then add it our list to be returned
                output.append(cls(dojo))
            return output

    # Get one dojo with all students
    @classmethod
    def get_one(cls, data):
        query = """
            SELECT *
            FROM dojos
            LEFT JOIN ninjas
                ON dojos.id = ninjas.dojo_id
            WHERE dojos.id=%(id)s
        """
        response = MySQLConnection(DATABASE).query_db(query, data)
        # Because we get a table back with repeating left joins
        # we need to instanciate the dojo first
        # Extract Dojo Attributes from response with dictionary
        dojo_data = {
            'id': response[0]['id'],
            'name': response[0]['name'],
            'created_at': response[0]['created_at'],
            'updated_at': response[0]['updated_at']
        }
        # Use classmethod to build dojo instance
        dojo_instance = cls(dojo_data)

        # Make an empty ninja list to be filled with instances
        # generated by the loop
        ninja_list = []
        if response:  # ensure we're getting data
            # Loop through list of responses
            for row in response:
                # Extract Ninja Attributes
                ninja_data = {
                    'id': row['ninjas.id'],
                    'first_name': row['first_name'],
                    'last_name': row['last_name'],
                    'age': row['age'],
                    'created_at': row['ninjas.created_at'],
                    'updated_at': row['ninjas.updated_at'],
                    'dojo_id': row['id']
                }

                # Use Ninja Class model to instanciate the Ninja
                ninja_instance = nm.Ninja(ninja_data)

                # Add it to our list
                ninja_list.append(ninja_instance)

        # Create dojo instance attribute filled with
        # a list of Ninja instances
        dojo_instance.ninjas = ninja_list

        return dojo_instance

    # Class method for adding dojos to the DB
    @classmethod
    def add_one(cls, data):
        query = """
            INSERT INTO dojos (name, created_at, updated_at)
            VALUES (%(name)s, NOW(), NOW())
        """
        return MySQLConnection(DATABASE).query_db(query, data)
